# Generated by Django 5.0.1 on 2024-01-14 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_systemreports_time_psychologistschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='methodists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__label': 'methodist'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
