# Generated by Django 4.2.7 on 2023-11-11 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_rename_login_time_connections_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MosRuAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('captcha', models.BooleanField(default=False)),
                ('captcha_url', models.CharField(max_length=20000, null=True)),
                ('status', models.CharField(choices=[('wait', 'Ожидание'), ('success', 'Успешно'), ('error', 'Ошибка'), ('wait_captcha', 'Капча')], max_length=20, null=True)),
                ('token', models.CharField(max_length=20000, null=True)),
            ],
        ),
    ]
