# Generated by Django 4.2.7 on 2023-11-11 10:53

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_account_is_developer_account_two_auth_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='mosruauth',
            name='uuid',
            field=models.CharField(default=Accounts.models.get_uuid, editable=False, max_length=3600, unique=True),
        ),
    ]
