# Generated by Django 4.2.7 on 2023-11-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_account_is_developer_connections_verify_and_more'),
    ]

    operations = [
    ]
