from . import aam
from . import admin
from . import other
from . import student
from . import teacher
from . import psychologist
from . import administration
from . import developer
from . import personalisation
from . import organizer
from . import statistics