# Generated by Django 4.2.7 on 2023-11-12 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0009_alter_events_type_alter_events_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomTeacherAuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clr', to='MainApp.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
