# Generated by Django 4.2.7 on 2023-11-20 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0012_systemreports_psychologistschedule_feedbackquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemreports',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PsychologistSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('comment', models.TextField(blank=True, max_length=2550, null=True)),
                ('child', models.ForeignKey(limit_choices_to=models.Q(('peculiarity__in', ['handicapped', 'autism'])),
                                            on_delete=django.db.models.deletion.CASCADE, related_name='child',
                                            to=settings.AUTH_USER_MODEL)),
                ('psychologist', models.ForeignKey(limit_choices_to={'role': 'psychologist'},
                                                   on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='psychologist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=2550)),
                ('answer', models.TextField(blank=True, max_length=2550, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(null=True)),
                ('answer_by',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_by',
                                   to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
