# Generated by Django 4.2.7 on 2023-11-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_mosruauth_account_is_developer_account_two_auth_and_more'),
    ]

    operations = [

    ]
